version: '3.9'

services:
  # 🧑 Users DB - stores registered users and credentials
  users_db:
    image: postgres:12-alpine
    container_name: users_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password
    ports:
      - "5433:5432"   # maps container's 5432 to localhost:5433
    volumes:
      - ./Services/UsersService/db/data:/var/lib/postgresql/data
      - ./Services/UsersService/db/migration:/db  # Optional: Mount migrations/scripts

  # 📋 Surveys DB - stores surveys, questions, options, and access policies
  surveys_db:
    image: postgres:12-alpine
    container_name: surveys_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: surveys_db
      POSTGRES_USER: surveys_user
      POSTGRES_PASSWORD: surveys_password
    ports:
      - "5434:5432"
    volumes:
      - ./Services/SurveysService/db/data:/var/lib/postgresql/data
      - ./Services/SurveysService/db/migration:/db  # Optional: Mount migrations/scripts

  # 🗳️ Voting DB - stores votes, batches, and voting state
  voting_db:
    image: postgres:12-alpine
    container_name: votes_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: votes_db
      POSTGRES_USER: votes_user
      POSTGRES_PASSWORD: votes_password
    ports:
      - "5435:5432"
    volumes:
      - ./Services/VotesService/db/data:/var/lib/postgresql/data
      - ./Services/VotesService/db/migration:/db  # Optional: Mount migrations/scripts

  # 📊 Results DB - stores aggregated and read-optimized results
  results_db:
    image: postgres:12-alpine
    container_name: results_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: results_db
      POSTGRES_USER: results_user
      POSTGRES_PASSWORD: results_password
    ports:
      - "5436:5432"
    volumes:
      - ./Services/ResultsService/db/data:/var/lib/postgresql/data
      - ./Services/ResultsService/db/migration:/db  # Optional: Mount migrations/scripts
