@startuml
hide circle
skinparam linetype ortho
skinparam classAttributeIconSize 0

' VoteBatch holds overall submission data
entity "VoteBatch" as VoteBatch {
  *id : UUID <<PK>>
  --
  survey_id : UUID  <<external>>
  user_id : UUID <<external>>
  voting_mode : enum('named', 'anonymous')
  is_submitted : boolean
  submitted_at : datetime
  updated_at : datetime
}

' Individual votes for each question
entity "Vote" as Vote {
  *id : UUID <<PK>>
  --
  user_id : UUID <<nullable>> <<external>>
  survey_id : UUID  <<external>>
  question_id : UUID <<external>>
  question_type : enum('single', 'range', 'text')
  ' for single-choice
  selected_option_id : UUID <<nullable>> <<external>>  
  ' for range
  range_value : int <<nullable>>                       
  ' for open
  open_text : text <<nullable>>                        
}

' Relations
VoteBatch ||--o{ Vote : contains

@enduml
